version: 2

project_name: hyde-config

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    main: ./main.go
    binary: "hyde-config"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      # - LICENSE # TODO: add license
      - README.md

nfpms:
  - vendor: "HyDE-Project"
    homepage: "https://github.com/HyDE-Project/hyde-config"
    maintainer: "HyDE-Project <contact@hyde-project.org>"
    description: "Hyde Configuration Parser and Watcher"
    license: "MIT"
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    section: utils
    priority: optional
    contents:
      - src: ./README.md
        dst: /usr/share/doc/hyde-config/README.md
      - src: ./hyde-config.service
        dst: /usr/lib/systemd/user/hyde-config.service
        file_info:
          mode: 0644

aurs:
  - name: hyde-config
    homepage: "https://github.com/HyDE-Project/hyde-config"
    description: "Hyde Configuration Parser and Watcher for HyDE Project"
    maintainers:
      - "HyDE-Project <contact@hyde-project.org>"
    license: "MIT"
    private_key: "{{ .Env.AUR_PRIVATE_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/hyde-config.git"
    depends:
      - glibc
    optdepends:
      - "systemd: for user service support"
    provides:
      - hyde-config
    conflicts:
      - hyde-config-git
    backup:
      - etc/hyde/config.toml
    package: |-
      # Install binary
      install -Dm755 hyde-config "${pkgdir}/usr/bin/hyde-config"
      
      # Install documentation
      install -Dm644 README.md "${pkgdir}/usr/share/doc/${pkgname}/README.md"
      
      # Install systemd user service
      install -Dm644 hyde-config.service "${pkgdir}/usr/lib/systemd/user/hyde-config.service"
    commit_author:
      name: "HyDE-Project Bot"
      email: "bot@hyde-project.org"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"